env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: off
  import/extensions: off
<<<<<<< HEAD
  no-restricted-syntax:
    - off
    - ForOfStatement
=======
  no-restricted-syntax: off
>>>>>>> parent of 0611af4 (rm rule)
