name: linter-check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: install dependencies
        run: make install
      - name: lint
        run: make lint
